---
version: '3'
services:
  clickhouse-exporter:
    image: dockerlocal.fh-njrd.top/cilckhouse-exporter:0.0.1
    restart: always
    network_mode: host
    container_name: clickhouse-exporter
    ports:
      - 9116:9116
    environment:
    ###此处写CK的user和password，注意不要加空格
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=123456
            ####此处为命令行启动docker时添加的参数，即和docker run xxxx -scrape_url=//xxx.xxx.xxx.xxx:xxxx等价
    ###写CK的host:port 本机启动
    command: -scrape_uri=http://pretest05.ovt.iot.fh-njrd.top:8123
